"""add llm_calls table

Revision ID: 327ae479ff24
Revises: 81158a202cb5
Create Date: 2026-08-29 17:48:56.503395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327ae479ff24'
down_revision: Union[str, Sequence[str], None] = '81158a202cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('id', sa.Uuid(), nullable=False, comment='LLM呼び出しの記録ID'),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_calls_kind_created_at', 'llm_calls', ['kind', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_llm_calls_kind_created_at', table_name='llm_calls')
    op.drop_table('llm_calls')
    # ### end Alembic commands ###
