"""add is_trial to llm_calls

Revision ID: 6d0fb98be55e
Revises: c4469f18869d
Create Date: 2026-09-06 10:01:08.584907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0fb98be55e'
down_revision: Union[str, Sequence[str], None] = 'c4469f18869d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_calls', sa.Column('is_trial', sa.Boolean(), nullable=False, comment='呼び出し時点で許可リスト外だったかどうか'))
    op.create_index('ix_llm_calls_is_trial_kind_created_at', 'llm_calls', ['is_trial', 'kind', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_llm_calls_is_trial_kind_created_at', table_name='llm_calls')
    op.drop_column('llm_calls', 'is_trial')
    # ### end Alembic commands ###
