"""embedding and updated_atを追加

Revision ID: 81158a202cb5
Revises: 93ef60bfe321
Create Date: 2026-08-25 10:02:59.340275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '81158a202cb5'
down_revision: Union[str, Sequence[str], None] = '93ef60bfe321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discoveries', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'))
    op.add_column('discoveries', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discoveries', 'embedding')
    op.drop_column('discoveries', 'updated_at')
    # ### end Alembic commands ###
