"""create discoveries

Revision ID: 93ef60bfe321
Revises: 
Create Date: 2026-08-16 19:33:38.030491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ef60bfe321'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discoveries',
    sa.Column('id', sa.Uuid(), nullable=False, comment='発見ID'),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('discovered_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discoveries_discovered_at', 'discoveries', ['discovered_at', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_discoveries_discovered_at', table_name='discoveries')
    op.drop_table('discoveries')
    # ### end Alembic commands ###
