"""add user_id to discoveries and llm_calls

Revision ID: c4469f18869d
Revises: e05433eef13d
Create Date: 2026-09-05 18:41:11.754524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4469f18869d'
down_revision: Union[str, Sequence[str], None] = 'e05433eef13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discoveries', sa.Column('user_id', sa.Uuid(), nullable=False, comment='ユーザーID'))
    op.drop_index(op.f('ix_discoveries_discovered_at'), table_name='discoveries')
    op.create_index('ix_user_id_discoveries_discovered_at', 'discoveries', ['user_id', 'discovered_at', 'created_at'], unique=False)
    op.add_column('llm_calls', sa.Column('user_id', sa.Uuid(), nullable=False, comment='ユーザーID'))
    op.create_index('ix_llm_calls_user_id_kind_created_at', 'llm_calls', ['user_id', 'kind', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_llm_calls_user_id_kind_created_at', table_name='llm_calls')
    op.drop_column('llm_calls', 'user_id')
    op.drop_index('ix_user_id_discoveries_discovered_at', table_name='discoveries')
    op.create_index(op.f('ix_discoveries_discovered_at'), 'discoveries', ['discovered_at', 'created_at'], unique=False)
    op.drop_column('discoveries', 'user_id')
    # ### end Alembic commands ###
