"""add source_urls to discoveries

Revision ID: e05433eef13d
Revises: 327ae479ff24
Create Date: 2026-08-30 23:36:19.602953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05433eef13d'
down_revision: Union[str, Sequence[str], None] = '327ae479ff24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discoveries', sa.Column('source_urls', sa.ARRAY(sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discoveries', 'source_urls')
    # ### end Alembic commands ###
